spring:
  security:
    oauth2:
      resourceserver:
        id: http://localhost:8080/players
        jwk:
          jwk-set-uri: https://maximodanilo.auth0.com/.well-known/jwks.json
          issuer-uri: https://maximodanilo.auth0.com/